-- BigManThing — Guess Nah seed (Dem Nah + Ting Nah).

-- ── Dem Nah (people + folklore) ─────────────────────────────────────────────
insert into public.entities
  (mode, name, aliases, type, domain, era, form, alignment, reach, status, description, difficulty)
values
  ('dem', 'Brian Lara', array['The Prince of Port of Spain','BCL'],
    'person', 'sports', 'y1950_2000', 'human', 'heroic', 'global', 'alive',
    'Trinidadian cricket batsman, holder of the highest individual Test score.', 'easy'),
  ('dem', 'Machel Montano', array['Machel','MMC'],
    'person', 'music', 'y1950_2000', 'human', 'heroic', 'global', 'alive',
    'King of soca and longtime soca monarch contender.', 'easy'),
  ('dem', 'Eric Williams', array['Doc','Father of the Nation'],
    'person', 'politics', 'y1900_1950', 'human', 'heroic', 'caribbean_wide', 'deceased',
    'First Prime Minister of Trinidad and Tobago.', 'medium'),
  ('dem', 'Dwayne Bravo', array['DJ Bravo'],
    'person', 'sports', 'y2000_plus', 'human', 'heroic', 'global', 'alive',
    'All-rounder cricketer and recording artist.', 'easy'),
  ('dem', 'Kees Dieffenthaller', array['Kes','Kes the Band'],
    'person', 'music', 'y2000_plus', 'human', 'heroic', 'caribbean_wide', 'alive',
    'Lead singer of Kes the Band, modern soca staple.', 'medium'),
  ('dem', 'Nicki Minaj', array['Onika Maraj'],
    'person', 'music', 'y2000_plus', 'human', 'mischievous', 'global', 'alive',
    'Trinidad-born hip-hop artist.', 'easy'),
  ('dem', 'Papa Bois', array['Papa Bwa','Father of the Forest'],
    'folklore', 'nature', 'timeless', 'humanoid', 'protector', 'trinidad_wide', 'mythical',
    'Half-man, half-beast guardian of the Trinidadian forest.', 'easy'),
  ('dem', 'Soucouyant', array['Soucriant','Old Higue'],
    'folklore', 'folklore', 'timeless', 'shapeshifter', 'sinister', 'trinidad_wide', 'mythical',
    'Old woman who sheds her skin and flies as a fireball to drink blood.', 'easy'),
  ('dem', 'La Diablesse', array['Lajables','Devil Woman'],
    'folklore', 'folklore', 'timeless', 'humanoid', 'sinister', 'trinidad_wide', 'mythical',
    'Beautiful woman with one cow foot who lures men into the bush.', 'easy'),
  ('dem', 'Moko Jumbie', array['Moko Jumbi'],
    'folklore', 'culture', 'pre_1900', 'humanoid', 'neutral', 'caribbean_wide', 'active_legend',
    'Stilt-walking carnival character of West African origin.', 'medium'),
  ('dem', 'Mama Dlo', array['Mama Dleau','Mama D''Leau'],
    'folklore', 'nature', 'timeless', 'shapeshifter', 'protector', 'trinidad_wide', 'mythical',
    'River-woman with a serpent''s tail who guards rivers and forests.', 'medium'),
  ('dem', 'Douen', array['Douens'],
    'folklore', 'folklore', 'timeless', 'humanoid', 'mischievous', 'trinidad_wide', 'mythical',
    'Spirits of children who died unbaptised — backwards feet, large straw hats.', 'medium')
;

-- ── Ting Nah (food + drink + instruments + objects) ─────────────────────────
insert into public.entities
  (mode, name, aliases, kind, heritage, era, material, occasion, sense, reach, description, difficulty)
values
  ('ting', 'Doubles', array[]::text[],
    'food', 'indian', 'y1900_1950', 'edible', 'everyday', 'taste', 'caribbean_wide',
    'Two flat fried bara filled with curried chickpeas. Trini breakfast champion.', 'easy'),
  ('ting', 'Buss Up Shot', array['Buss-Up-Shut','Paratha Roti'],
    'food', 'indian', 'y1900_1950', 'edible', 'everyday', 'taste', 'trinidad_wide',
    'Shredded paratha roti served with curry.', 'easy'),
  ('ting', 'Bake and Shark', array['Shark and Bake'],
    'food', 'creole', 'y1950_2000', 'edible', 'special', 'taste', 'trinidad_wide',
    'Fried bake stuffed with shark, famously sold at Maracas.', 'easy'),
  ('ting', 'Pelau', array[]::text[],
    'food', 'creole', 'pre_1900', 'edible', 'everyday', 'taste', 'caribbean_wide',
    'One-pot rice with browned meat, peas, coconut milk.', 'easy'),
  ('ting', 'Callaloo', array[]::text[],
    'food', 'african', 'pre_1900', 'edible', 'everyday', 'taste', 'caribbean_wide',
    'Leafy green stew with okra and crab or salt meat.', 'easy'),
  ('ting', 'Mauby', array['Mavi'],
    'drink', 'indigenous', 'pre_1900', 'liquid', 'everyday', 'taste', 'caribbean_wide',
    'Bittersweet bark-based drink served ice cold.', 'easy'),
  ('ting', 'Sorrel', array['Roselle'],
    'drink', 'african', 'pre_1900', 'liquid', 'holiday', 'taste', 'caribbean_wide',
    'Spiced hibiscus drink served at Christmas.', 'easy'),
  ('ting', 'Ponche de Crème', array['Ponche-de-Crème','Ponche'],
    'drink', 'european', 'y1900_1950', 'liquid', 'holiday', 'taste', 'trinidad_wide',
    'Trini eggnog with rum, served at Christmas.', 'medium'),
  ('ting', 'Steelpan', array['Pan','Steel Drum'],
    'instrument', 'african', 'y1900_1950', 'metal', 'carnival', 'sound', 'global',
    'Trinidadian invention played in steelbands; the national instrument.', 'easy'),
  ('ting', 'Tassa', array['Tassa Drum'],
    'instrument', 'indian', 'pre_1900', 'wood', 'religious', 'sound', 'trinidad_wide',
    'Indo-Caribbean kettledrum played at Hosay and weddings.', 'medium'),
  ('ting', 'Cuatro', array[]::text[],
    'instrument', 'european', 'pre_1900', 'wood', 'holiday', 'sound', 'trinidad_wide',
    'Small four-string guitar central to parang music.', 'medium'),
  ('ting', 'Carnival Costume', array['Mas Costume','Pretty Mas'],
    'wearable', 'creole', 'y1950_2000', 'fabric', 'carnival', 'sight', 'trinidad_wide',
    'Bedazzled bikini-feather-bead costume worn on Carnival Tuesday.', 'easy'),
  ('ting', 'Dingolay Flag', array['National Flag'],
    'wearable', 'creole', 'y1950_2000', 'fabric', 'special', 'sight', 'trinidad_wide',
    'Red, white, and black flag waved at fetes and matches.', 'medium'),
  ('ting', 'Cocoyea Broom', array['Cocoyea'],
    'tool_object', 'african', 'pre_1900', 'wood', 'everyday', 'touch', 'trinidad_wide',
    'Stiff broom made of dried coconut palm spines.', 'medium')
;
