-- The current people draft roster is versioned in migrations and content/people-draft.json.
-- Do not auto-publish answers or fabricate approved biographies on reset.
-- Existing hosted legacy entities and history are preserved by the additive migration.
