-- BigManThing — Guess Nah seed (Dem Nah + Ting Nah).

-- ── Dem Nah (people only — 8-column hybrid system) ──────────────────────────
-- Columns: field, role, role_group, era, gender, status, domain_type, output_context, region
insert into public.entities
  (mode, name, aliases, field, role, role_group, era, gender, status,
   domain_type, output_context, region, description, difficulty)
values
  ('dem', 'Brian Lara', array['The Prince of Port of Spain','BCL'],
    'sports', 'cricketer', 'athlete', 'y1980_1999', 'male', 'retired',
    'elite_global_performer', 'stadium_sport', 'trinidad_north',
    'Trinidadian cricket batsman, holder of the highest individual Test score.', 'easy'),
  ('dem', 'Machel Montano', array['Machel','MMC'],
    'music', 'soca_artist', 'musician', 'y1980_1999', 'male', 'active',
    'international_professional', 'live_performance', 'trinidad_north',
    'King of soca and longtime soca monarch contender.', 'easy'),
  ('dem', 'Eric Williams', array['Doc','Father of the Nation'],
    'politics', 'prime_minister', 'politician', 'pre_1980', 'male', 'deceased',
    'cultural_legend', 'political_office', 'trinidad_north',
    'First Prime Minister of Trinidad and Tobago.', 'medium'),
  ('dem', 'Dwayne Bravo', array['DJ Bravo'],
    'sports', 'cricketer', 'athlete', 'y2000_2009', 'male', 'retired',
    'elite_global_performer', 'stadium_sport', 'trinidad_central',
    'All-rounder cricketer and recording artist.', 'easy'),
  ('dem', 'Kees Dieffenthaller', array['Kes','Kes the Band'],
    'music', 'soca_artist', 'musician', 'y2000_2009', 'male', 'active',
    'regional_icon', 'live_performance', 'trinidad_north',
    'Lead singer of Kes the Band, modern soca staple.', 'medium'),
  ('dem', 'Nicki Minaj', array['Onika Maraj'],
    'music', 'rapper', 'musician', 'y2000_2009', 'female', 'active',
    'elite_global_performer', 'studio_music', 'trinidad_south',
    'Trinidad-born hip-hop artist.', 'easy'),
  ('dem', 'Hasely Crawford', array[]::text[],
    'sports', 'sprinter', 'athlete', 'pre_1980', 'male', 'retired',
    'elite_global_performer', 'stadium_sport', 'trinidad_north',
    'Trinidad''s first Olympic gold medalist — 100m at Montreal 1976.', 'medium'),
  ('dem', 'Dwight Yorke', array[]::text[],
    'sports', 'footballer', 'athlete', 'y1980_1999', 'male', 'retired',
    'elite_global_performer', 'stadium_sport', 'tobago',
    'Tobago-born striker who won the Treble with Manchester United.', 'easy'),
  ('dem', 'Sparrow', array['Mighty Sparrow','Slinger Francisco'],
    'music', 'calypso_artist', 'musician', 'pre_1980', 'male', 'retired',
    'cultural_legend', 'live_performance', null,
    'Calypso King of the World, the most successful calypsonian ever.', 'easy'),
  ('dem', 'Bunji Garlin', array['Bunji','Ian Alvarez'],
    'music', 'soca_artist', 'musician', 'y2000_2009', 'male', 'active',
    'international_professional', 'live_performance', 'trinidad_north',
    'Viking of soca, known for high-energy power soca.', 'medium'),
  ('dem', 'Fay-Ann Lyons', array['Fay-Ann'],
    'music', 'soca_artist', 'musician', 'y2000_2009', 'female', 'active',
    'regional_icon', 'live_performance', 'trinidad_north',
    'Soca queen, International Soca Monarch winner, married to Bunji.', 'medium'),
  ('dem', 'Keith Rowley', array['Rowley','PM Rowley'],
    'politics', 'prime_minister', 'politician', 'y2010_2019', 'male', 'active',
    'national_figure', 'political_office', 'tobago',
    'Current PNM leader and Prime Minister of T&T.', 'easy'),
  ('dem', 'Kamla Persad-Bissessar', array['Kamla','KPB'],
    'politics', 'prime_minister', 'politician', 'y2010_2019', 'female', 'active',
    'national_figure', 'political_office', 'trinidad_central',
    'First female PM of T&T, UNC leader.', 'medium'),
  ('dem', 'Heather Headley', array[]::text[],
    'entertainment', 'singer', 'musician', 'y1980_1999', 'female', 'active',
    'elite_global_performer', 'live_performance', 'tobago',
    'Trinidad-born Tony and Grammy award-winning performer.', 'hard'),
  ('dem', 'Sunil Narine', array[]::text[],
    'sports', 'cricketer', 'athlete', 'y2010_2019', 'male', 'active',
    'elite_global_performer', 'stadium_sport', 'trinidad_north',
    'Mystery spinner and T20 superstar from Trinidad.', 'medium'),
  ('dem', 'Anya Ayoung-Chee', array['Anya'],
    'entertainment', 'designer', 'entertainer', 'y2010_2019', 'female', 'active',
    'international_professional', 'digital_content', 'trinidad_north',
    'Miss Universe Trinidad and Project Runway winner.', 'hard'),
  ('dem', 'Patrice Roberts', array[]::text[],
    'music', 'soca_artist', 'musician', 'y2010_2019', 'female', 'active',
    'regional_icon', 'live_performance', null,
    'Soca sensation and carnival favourite.', 'medium'),
  ('dem', 'Wendy Fitzwilliam', array[]::text[],
    'entertainment', 'beauty_queen', 'entertainer', 'y1980_1999', 'female', 'active',
    'elite_global_performer', 'live_performance', 'tobago',
    'Miss Universe 1998 from Trinidad and Tobago.', 'medium'),
  ('dem', 'Basdeo Panday', array['Panday','Bas'],
    'politics', 'prime_minister', 'politician', 'y1980_1999', 'male', 'deceased',
    'national_figure', 'political_office', 'trinidad_central',
    'First Indo-Trinidadian PM, UNC founder.', 'medium'),
  ('dem', 'Rudolph Charles', array['Charles'],
    'sports', 'footballer', 'athlete', 'y2000_2009', 'male', 'retired',
    'international_professional', 'stadium_sport', null,
    'Key member of the 2006 Soca Warriors World Cup squad.', 'hard'),
  ('dem', 'Kibwe Trim', array['Kibwe'],
    'social_media', 'influencer', 'creator', 'y2020_plus', 'male', 'active',
    'local_creator', 'digital_content', 'trinidad_north',
    'Trini content creator and social media personality.', 'medium'),
  ('dem', 'Voice', array['Aaron St. Louis'],
    'music', 'soca_artist', 'musician', 'y2010_2019', 'male', 'active',
    'regional_icon', 'studio_music', null,
    'Modern soca artist, won Road March with "Far From Finished".', 'medium')
;

-- ── Folklore entities (Draw Nah only, NOT in Guess Nah) ─────────────────────
insert into public.entities
  (mode, name, aliases, era, description, difficulty,
   guess_nah_enabled, draw_nah_enabled)
values
  ('dem', 'Papa Bois', array['Papa Bwa','Father of the Forest'],
    'pre_1980',
    'Half-man, half-beast guardian of the Trinidadian forest.', 'easy',
    false, true),
  ('dem', 'Soucouyant', array['Soucriant','Old Higue'],
    'pre_1980',
    'Old woman who sheds her skin and flies as a fireball to drink blood.', 'easy',
    false, true),
  ('dem', 'La Diablesse', array['Lajables','Devil Woman'],
    'pre_1980',
    'Beautiful woman with one cow foot who lures men into the bush.', 'easy',
    false, true),
  ('dem', 'Moko Jumbie', array['Moko Jumbi'],
    'pre_1980',
    'Stilt-walking carnival character of West African origin.', 'medium',
    false, true),
  ('dem', 'Mama Dlo', array['Mama Dleau','Mama D''Leau'],
    'pre_1980',
    'River-woman with a serpent''s tail who guards rivers and forests.', 'medium',
    false, true),
  ('dem', 'Douen', array['Douens'],
    'pre_1980',
    'Spirits of children who died unbaptised — backwards feet, large straw hats.', 'medium',
    false, true)
;

-- ── Ting Nah (food + drink + instruments + objects) ─────────────────────────
insert into public.entities
  (mode, name, aliases, kind, heritage, era, material, occasion, sense, reach, description, difficulty)
values
  ('ting', 'Doubles', array[]::text[],
    'food', 'indian', 'y1900_1950', 'edible', 'everyday', 'taste', 'caribbean_wide',
    'Two flat fried bara filled with curried chickpeas. Trini breakfast champion.', 'easy'),
  ('ting', 'Buss Up Shot', array['Buss-Up-Shut','Paratha Roti'],
    'food', 'indian', 'y1900_1950', 'edible', 'everyday', 'taste', 'trinidad_wide',
    'Shredded paratha roti served with curry.', 'easy'),
  ('ting', 'Bake and Shark', array['Shark and Bake'],
    'food', 'creole', 'y1950_2000', 'edible', 'special', 'taste', 'trinidad_wide',
    'Fried bake stuffed with shark, famously sold at Maracas.', 'easy'),
  ('ting', 'Pelau', array[]::text[],
    'food', 'creole', 'pre_1900', 'edible', 'everyday', 'taste', 'caribbean_wide',
    'One-pot rice with browned meat, peas, coconut milk.', 'easy'),
  ('ting', 'Callaloo', array[]::text[],
    'food', 'african', 'pre_1900', 'edible', 'everyday', 'taste', 'caribbean_wide',
    'Leafy green stew with okra and crab or salt meat.', 'easy'),
  ('ting', 'Mauby', array['Mavi'],
    'drink', 'indigenous', 'pre_1900', 'liquid', 'everyday', 'taste', 'caribbean_wide',
    'Bittersweet bark-based drink served ice cold.', 'easy'),
  ('ting', 'Sorrel', array['Roselle'],
    'drink', 'african', 'pre_1900', 'liquid', 'holiday', 'taste', 'caribbean_wide',
    'Spiced hibiscus drink served at Christmas.', 'easy'),
  ('ting', 'Ponche de Crème', array['Ponche-de-Crème','Ponche'],
    'drink', 'european', 'y1900_1950', 'liquid', 'holiday', 'taste', 'trinidad_wide',
    'Trini eggnog with rum, served at Christmas.', 'medium'),
  ('ting', 'Steelpan', array['Pan','Steel Drum'],
    'instrument', 'african', 'y1900_1950', 'metal', 'carnival', 'sound', 'global',
    'Trinidadian invention played in steelbands; the national instrument.', 'easy'),
  ('ting', 'Tassa', array['Tassa Drum'],
    'instrument', 'indian', 'pre_1900', 'wood', 'religious', 'sound', 'trinidad_wide',
    'Indo-Caribbean kettledrum played at Hosay and weddings.', 'medium'),
  ('ting', 'Cuatro', array[]::text[],
    'instrument', 'european', 'pre_1900', 'wood', 'holiday', 'sound', 'trinidad_wide',
    'Small four-string guitar central to parang music.', 'medium'),
  ('ting', 'Carnival Costume', array['Mas Costume','Pretty Mas'],
    'wearable', 'creole', 'y1950_2000', 'fabric', 'carnival', 'sight', 'trinidad_wide',
    'Bedazzled bikini-feather-bead costume worn on Carnival Tuesday.', 'easy'),
  ('ting', 'Dingolay Flag', array['National Flag'],
    'wearable', 'creole', 'y1950_2000', 'fabric', 'special', 'sight', 'trinidad_wide',
    'Red, white, and black flag waved at fetes and matches.', 'medium'),
  ('ting', 'Cocoyea Broom', array['Cocoyea'],
    'tool_object', 'african', 'pre_1900', 'wood', 'everyday', 'touch', 'trinidad_wide',
    'Stiff broom made of dried coconut palm spines.', 'medium')
;
